<?php
    $andrew = array ('name'=> 'Andrew', 'password' => '123', 'result' => array("auto", "blowoutservices", "bicycles"));
    // $andy = array ('name'=> 'Andy', 'password' => '555', 'result' => array("beaches","beachvolleyball","bicyclepaths","bikerentals","boating","bowling","bungeejumping","carousels","challengecourses","homeservices","blinds","buildingsupplies","cabinetry","carpenters","carpeting","carpetinstallation","childproofing","chimneysweeps","contractors","countertopinstall","damagerestoration","decksrailing","demolitionservices","doorsales","drywall","electricians","fencesgates","fireplace","fireprotection","firewood","flooring","furnitureassembly","garage_door_services","gardeners","glassandmirrors","gutterservices","handyman","home_inspectors","home_organization","homeautomation","homecleaning","homenetworkinstall","hometheatreinstallation","homewindowtinting","housesitters","hvac","insulationinstallation","interiordesign","irrigation","landscapearchitects","landscaping","lighting","locksmiths","masonry_concrete","movers","painters","patiocoverings","plumbing","poolcleaners","poolservice","pressurewashers","realestate","apartments","artspacerentals","commercialrealestate","estateliquidation","homestaging","kitchenincubators","mobilehomes","mobileparks","mortgagebrokers","propertymgmt","realestateagents","realestatesvcs","sharedofficespaces","university_housing","refinishing","roofing","roofinspectors","seasonaldecorservices","securitysystems","shutters","solarinstallation","structuralengineers","stucco","televisionserviceproviders","tiling","treeservices","utilities","vinylsiding","waterheaterinstallrepair","waterproofing","waterpurification","windowsinstallation","windowwashing"));
    $andy = array ('name'=> 'Andy', 'password' => '555', 'result' => array("diving","freediving","scuba","barreclasses","tofu","jpsweets","taiyaki","milkshakebars","nasilemak"));
    $nick = array ('name'=> 'Nick', 'password' => '987', 'result' => array("health","homeservices","hotelstravel","localflavor"));
    // echo $arr['name'];
    if ($_POST['name'] == $andrew['name'] && $_POST['password'] == $andrew['password']) echo  json_encode($andrew['result']);;
    if ($_POST['name'] == $nick['name'] && $_POST['password'] == $nick['password']) echo  json_encode($nick['result']);;
    if ($_POST['name'] == $andy['name'] && $_POST['password'] == $andy['password']) echo  json_encode($andy['result']);;

?>